apps/master_budget/passives/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        'savings-liabilities/scenarios/',
        views.scenarios_savings_liabilities,
        name="scenarios_savings_liabilities"
    ),
    path(
        'savings-liabilities/scenario/detail/<int:id>/',
        views.scenario_savings_liabilities,
        name="scenario_savings_liabilities"
    ),
    path(
        'savings-liabilities/scenario/detail/comments/<int:id>/',
        views.scenario_savings_liabilities_comments,
        name="scenario_savings_liabilities_comments"
    ),
    path(
        'liabilities-loans/scenarios/',
        views.scenarios_liabilities_loans,
        name="scenarios_liabilities_loans"
    ),
    path(
        'liabilities-loans/scenario/detail/<int:id>/',
        views.scenario_liabilities_loans,
        name="scenario_liabilities_loans"
    ),
    path(
        'liabilities-loans/scenario/detail/comments/<int:id>/',
        views.scenario_liabilities_loans_comments,
        name="scenario_liabilities_loans_comments"
    ),
    path(
        'others-passives/scenarios/', views.scenarios_others_passives, name="scenarios_others_passives" # NOQA
    ),
    path(
        'others-passives/scenario/detail/<int:id>/',
        views.scenario_others_passives,
        name="scenario_others_passives"
    ),
]

apps/master_budget/patrimony/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('scenarios/', views.scenarios_equity, name="scenarios_equity"),
    path('scenario/detail/<int:id>/', views.scenario_equity, name="scenario_equity"),
    path('surplus/', views.surplus, name="surplus"),
    path('surplus/detail/<int:id>/', views.surplus_detail, name="surplus_detail")
]

apps/master_budget/urls.py
from django.urls import path
from apps.master_budget.views import (
    master_budget_dashboard,
    projection_parameters,
    projection_parameter,
    profit_loss_report_complementary_projection,
    profit_loss_report_complementary_projection_detail
)

urlpatterns = [
    path('', master_budget_dashboard, name="master_budget_dashboard"),
    path(
        'projection-parameters-list/',
        projection_parameters,
        name="projection_parameters"
    ),
    path(
        'projection-parameter-edit/<int:id>/',
        projection_parameter,
        name="projection_parameter"
    ),
    path(
        'profit-and-loss-reports/complementary-projection-list',
        profit_loss_report_complementary_projection,
        name="profit_loss_report_complementary_projection"
    ),
    path(
        'profit-and-loss-reports/complementary-projection-detail/<int:period_id>/',
        profit_loss_report_complementary_projection_detail,
        name="profit_loss_report_complementary_projection_detail"
    ),
]

ppto_safa/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.conf.urls import (
    handler404,
    handler500,
    handler403
)

from apps.main.views import error_500, error_404, error_403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('administration/', include('apps.administration.urls')),
    path('security/', include('apps.security.urls')),
    path('expenses-budgets/', include('apps.expenses_budgets.urls')),
    path('travel-budgets/', include('apps.travel_budgets.urls')),
    path('investment-budgets/', include('apps.investment_budgets.urls')),
    path('staff-budgets/', include('apps.staff_budgets.urls')),
    path('indirect-budgets/', include('apps.indirect_budgets.urls')),
    path('income-budgets/', include('apps.income_budgets.urls')),
    path('cost-budgets/', include('apps.cost_budgets.urls')),
    path('goals/', include('apps.goals.urls')),
    path('master-budget/', include('apps.master_budget.urls')),
    path(
        'master-budget/loan-portfolio/',
        include('apps.master_budget.loan_portfolio.urls')
    ),
    path(
        'master-budget/passives/',
        include('apps.master_budget.passives.urls')
    ),
    path(
        'master-budget/non-performing-assets/',
        include('apps.master_budget.non_performing_assets.urls')
    ),
    path(
        'master-budget/payment-payroll/',
        include('apps.master_budget.payment_payroll.urls')
    ),
    path(
        'master-budget/equity/',
        include('apps.master_budget.patrimony.urls')
    ),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
) + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

handler403 = error_403  # NOQA
handler404 = error_404  # NOQA
handler500 = error_500  # NOQA

apps/master_budget/forms.py
from django import forms

from apps.main.models import Periodo
from .models import MasterParameters
from utils.constants import STATUS


class MasterParametersForm(forms.ModelForm):
    date_base = forms.DateField(
        label="Fecha Base",
        required=True,
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    is_active = forms.ChoiceField(
        label="Estado",
        required=True,
        choices=STATUS,
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    period_id = forms.ModelChoiceField(
        label="Periodo",
        queryset=Periodo.objects.filter(habilitado=True),
        empty_label="--- Seleccione Periodo ---",
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    comment = forms.CharField(
        label="Comentario",
        widget=forms.Textarea(
            attrs={"rows": 3, "style": 'resize:none', 'class': 'form-control'}
        )
    )

    class Meta:
        model = MasterParameters
        fields = (
            'date_base',
            'period_id',
            'is_active',
            'comment',
        )


class MasterParametersEditForm(forms.ModelForm):
    date_base = forms.DateField(
        label="Fecha Base",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'date'})
    )
    is_active = forms.ChoiceField(
        label="Estado",
        required=True,
        choices=STATUS,
        widget=forms.Select(
            attrs={'class': 'form-select', 'style': 'width:100%'}
        )
    )
    comment = forms.CharField(
        label="Comentario",
        widget=forms.Textarea(
            attrs={"rows": 3, "style": 'resize:none', 'class': 'form-control'}
        )
    )

    class Meta:
        model = MasterParameters
        fields = (
            'date_base',
            'is_active',
            'comment',
        )

apps/master_budget/loan_portfolio/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from decimal import Decimal as dc

from .models import (
    LoanPortfolioScenario, LoanPortfolioCategory, LoanPortfolioCategoryMap,
    LoanPortfolioComment, LoanPortfolio, FinancialInvestmentsCategory,
    FinancialInvestments, FinancialInvestmentsComment, FinancialInvestmentsScenario
)
from .forms import (
    LoanPortfolioScenarioForm, ScenarioCloneForm, ScenarioCloneUpdateParameterForm,
    FinancialInvestmentsScenarioForm, FinancialInvestmentsScenarioCloneForm,
)
from apps.master_budget.models import MasterParameters
from utils.pagination import pagination
from utils.constants import (
    STATUS_SCENARIO, LIST_LOAN_PORTFOLIO_FIELDS, LIST_FINANCIAL_INVESTMENTS_FIELDS
)
from utils.sql import execute_sql_query
from .calculations import LoanPortfolioCalculations


@login_required()
@permission_required('ppto_maestro.puede_listar_categorias_prestamos', raise_exception=True)
def categories_loan_portfolio(request):
    def _execute_type():
        query = 'EXEC dbo.sp_pptoMaestroCarteraCredCatTipoPrestamoObtenerCatalogo'
        return execute_sql_query(query)

    def _find_data():
        category = request.POST.get('category', 'No Categoria')
        types_of_loans = request.POST.getlist('types_of_loans[]')
        types_list = []
        result_types = _execute_type()
        types = result_types.get('data')

        for item in types:
            if str(item.get('Id')) in types_of_loans:
                types_list.append(item)

        return category, types_list

    if request.is_ajax():
        result = _execute_type()
        data = []
        if result.get('status') == 'ok':
            codes = list(LoanPortfolioCategoryMap.objects.values_list('code', flat=True))
            data = list(result.get('data'))
            for key, value in enumerate(data):
                if value.get('Id') in codes:
                    data.pop(key)
        ctx = {
            'data': data
        }
        return HttpResponse(json.dumps(ctx, cls=DjangoJSONEncoder))

    if request.method == 'POST':
        if not request.user.has_perm('ppto_maestro.puede_crear_categorias_prestamos'):
            raise PermissionDenied
        category, types_of_loans = _find_data()
        _new_cat = LoanPortfolioCategory()
        _new_cat.code_core = 0
        _new_cat.name = category
        _new_cat.is_active = True
        _new_cat.identifier = category.lower()
        _new_cat.created_by = request.user
        _new_cat.updated_by = request.user
        _new_cat.save()

        for item in types_of_loans:
            LoanPortfolioCategoryMap.objects.create(
                category_id=_new_cat,
                name=item.get('Nombre'),
                code=item.get('Id'),
                created_by=request.user,
                updated_by=request.user
            )
        messages.success(request, 'Categoria agregada con éxito!')
    qs_categories = LoanPortfolioCategory.objects.all()
    ctx = {
        'qs_categories': qs_categories
    }
    return render(request, 'loan_portfolio/category/list.html', ctx)


@login_required()
@permission_required('ppto_maestro.puede_editar_categorias_prestamos', raise_exception=True)
def category_loan_portfolio(request, id):
    qs = get_object_or_404(LoanPortfolioCategory, pk=id)

    def _execute_type():
        query = 'EXEC dbo.sp_pptoMaestroCarteraCredCatTipoPrestamoObtenerCatalogo'
        return execute_sql_query(query)

    def _find_data():
        types_of_loans = request.POST.getlist('types_of_loans[]')
        types_list = []
        result_types = _execute_type()
        types = result_types.get('data')

        for item in types:
            if str(item.get('Id')) in types_of_loans:
                types_list.append(item)
        return types_list

    if request.method == 'POST':
        types_of_loans = _find_data()
        qs.name = request.POST.get('category')
        qs.save()
        LoanPortfolioCategoryMap.objects.filter(category_id=qs.pk).delete()
        for item in types_of_loans:
            LoanPortfolioCategoryMap.objects.create(
                category_id=qs,
                name=item.get('Nombre'),
                code=item.get('Id'),
                created_by=request.user,
                updated_by=request.user
            )
        messages.success(request, 'Categoria editada con éxito!')

    qs_detail = LoanPortfolioCategoryMap.objects.filter(
        category_id=qs.pk
    ).values_list('code', flat=True)

    result = _execute_type()

    ctx = {
        'qs': qs,
        'qs_detail': qs_detail,
        'result': result.get('data')
    }
    return render(request, 'loan_portfolio/category/edit.html', ctx)


@login_required()
@permission_required('ppto_maestro.puede_listar_cartera_crediticia', raise_exception=True)
def scenarios_loan_portfolio(request):
    form = LoanPortfolioScenarioForm()

    def _get_amount_base(parameter_id, category_id):
        amount = 0
        query = (
            f'EXEC dbo.sp_pptoMaestroCarteraCredCatObtenerSaldoCarteraHist '
            f'@ParametroId = {parameter_id}, @CategoriaId = {category_id}'
        )
        result = execute_sql_query(query)
        if result.get('status') != 'ok':
            return amount
        data = result.get('data')
        amount = data[0].get('SaldoCartera')
        return amount

    def _correlative(category_name, period, total):
        return f'ESC-{category_name[:4].upper()}-{period}-{total}'

    if request.method == 'POST':
        if request.POST.get('method') == 'create':
            if not request.user.has_perm('ppto_maestro.puede_crear_escenarios_cartera_crediticia'):
                raise PermissionDenied
            form = LoanPortfolioScenarioForm(request.POST)
            if not form.is_valid():
                messages.warning(
                    request, f'Formulario no válido: {form.errors.as_text()}'
                )
            else:
                if request.POST.get('is_active') == 'True':
                    LoanPortfolioScenario.objects.filter(
                        parameter_id=request.POST.get('parameter_id'),
                        category_id=request.POST.get('category_id')
                    ).update(is_active=False)
                _new = form.save()
                _new.period_id = _new.parameter_id.period_id
                _new.created_by = request.user
                _new.updated_by = request.user
                _new.save()
                category_name = _new.category_id.name
                period = _new.parameter_id.period_id.descperiodo
                total = LoanPortfolioScenario.objects.filter(
                    period_id=_new.period_id, category_id=_new.category_id
                ).count()
                correlative = _correlative(category_name, period, total)
                _new.correlative = correlative
                _new.save()
                _new.base_amount = _get_amount_base(
                    _new.parameter_id.pk, _new.category_id.pk
                )
                _new.annual_growth_percentage = 0
                _new.annual_growth_amount = 0
                _new.save()

                messages.success(request, 'Escenario creado con éxito!')
                redirect_url = reverse('scenario_loan_portfolio', kwargs={'id': _new.pk})
                full_redirect_url = f'{redirect_url}?option=open_calculations_modal'
                return redirect(full_redirect_url)

        elif request.POST.get('method') == 'clone':
            if not request.user.has_perm('ppto_maestro.puede_editar_escenarios_cartera_crediticia'):
                raise PermissionDenied
            id = request.POST.get('id')
            comment = request.POST.get('comment')
            is_active = request.POST.get('is_active')
            qs_old_esc = get_object_or_404(LoanPortfolioScenario, pk=id)
            _clone = LoanPortfolioScenario.objects.get(pk=id)
            _clone.pk = None
            _clone.save()
            if is_active == 'True':
                LoanPortfolioScenario.objects.filter(
                    parameter_id=_clone.parameter_id.pk,
                    category_id=_clone.category_id.pk
                ).update(is_active=False)
            total = LoanPortfolioScenario.objects.filter(
                period_id=_clone.period_id,
                category_id=_clone.category_id
            ).count()
            _clone.comment = comment
            _clone.is_active = is_active
            _clone.created_by = request.user
            _clone.updated_by = request.user
            _clone.correlative = _correlative(
                _clone.category_id.name,
                _clone.parameter_id.period_id.descperiodo, total
            )
            _clone.save()
            _clone.refresh_from_db()
            for item in range(1, 13):
                old_item = LoanPortfolio.objects.filter(
                    scenario_id=qs_old_esc.pk, month=item
                ).first()
                _upd = LoanPortfolio.objects.filter(
                    scenario_id=_clone.pk, month=item
                ).first()
                _upd.amount_initial = old_item.amount_initial
                _upd.percent_growth = old_item.percent_growth
                _upd.amount_growth = old_item.amount_growth
                _upd.rate = old_item.rate
                _upd.term = old_item.term
                _upd.percentage_arrears = old_item.percentage_arrears
                _upd.commission_percentage = old_item.commission_percentage
                _upd.level_quota = old_item.level_quota
                _upd.total_interest = old_item.total_interest

apps/master_budget/templates/MB_projection_parameters/add.html
<div class="modal fade" id="addProjectionModal" tabindex="-1" aria-labelledby="addProjectionModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title fw-light">Crear Proyección</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="POST">
        <div class="modal-body">
          {% csrf_token %}
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          <div class="row">
            {% for field in form.visible_fields  %}
            <div class="col-md-6">
              <div class="form-group mb-3">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                  <small class="text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                  <p class="text-danger">{{ error }}</p>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-safa">Aceptar</button>
        </div>
      </form>
    </div>
  </div>
</div>

apps/master_budget/templates/MB_projection_parameters/delete.html
<div class="modal fade" id="deleteProjectionModal" tabindex="-1" aria-labelledby="deleteProjectionModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title fw-light">Borrar Proyección</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="POST" id="deleteProjectionForm">
        <div class="modal-body">
          {% csrf_token %}
          <input type="hidden" name="method" value="delete">
          <h4 class="fw-light fs-5">¿Desea borrar parametro de Proyección?</h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-safa">Aceptar</button>
        </div>
      </form>
    </div>
  </div>
</div>

apps/master_budget/templates/MB_projection_parameters/edit.html
{% extends 'master_budget/layout/base.html' %}
{% load static %}

{% block title %}Editar Parametros de Proyección {% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item text-white ">
  <a href="{% url 'projection_parameters' %}" class="text-white text-decoration-none">/ Parametros de Proyección</a>
</li>
<li class="breadcrumb-item active text-white before-none" aria-current="page"> / Editar</li>
{% endblock breadcrumb %}

{% block content %}
<div class="container-fluid pt-4">
  <div class="card card-template">
    <div class="card-header">
      <div class="row">
        <div class="col-md-4">
          <h5 class="card-title fw-light fs-4">Editar Parametros de Proyección</h5>
        </div>
      </div>
    </div>
    <div class="card-body">
      <form method="post">
        <input type="hidden" name="method" value="edit">
        {% csrf_token %}
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          <div class="row">
            {% for field in form.visible_fields  %}
            <div class="col-md-6">
              <div class="form-group mb-3">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                  <small class="text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                  <p class="text-danger">{{ error }}</p>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="row">
            <div class="col-md-12">
              <button type="submit" class="btn btn-safa float-end">Aceptar</button>
            </div>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
  $(document).ready(()=>{
    
  })
</script>
{% endblock javascript %}

apps/master_budget/templates/MB_projection_parameters/list.html
{% extends 'master_budget/layout/base.html' %}
{% load static %}

{% block title %}Parametros de Proyección {% endblock title %}

{% block breadcrumb %}
  <li class="breadcrumb-item active text-white" aria-current="page">/ Parametros de Proyección</li>
{% endblock breadcrumb %}

{% block content %}
{% include 'MB_projection_parameters/add.html' %}
{% include 'MB_projection_parameters/delete.html' %}
<div class="container-fluid pt-4">
  <div class="card card-template">
    <div class="card-header">
      <div class="row">
        <div class="col-md-4">
          <h5 class="card-title fw-light fs-4">Parametros de Proyección</h5>
        </div>
        <div class="col-md-2">
          <button class="btn btn-outline-safa" id="btnAddProjectionParameter">
            Crear Proyección
          </button>
        </div>
        <div class="col-md-6">
          {% include 'master_budget/shared/search_form_with_period.html' %}
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-12">
          <div class="table-responsive">
            <table class="table table-hover table-bordered table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Periodo</th>
                  <th>Fecha Base</th>
                  <th>Correlativo</th>
                  <th>Estado</th>
                  <th class="text-center">Acción</th>
                </tr>
              </thead>
              <tbody>
                {% for item in result %}
                <tr>
                  <td>{{forloop.counter}}</td>
                  <td>{{item.period_id.descperiodo}}</td>
                  <td>{{item.date_base|date:'d/m/Y'}}</td>
                  <td>{{item.correlative}}</td>
                  <td>{{item.is_active|yesno:'Activo, Inactivo'}}</td>
                  <td class="text-center">
                    <div class="d-grid gap-2 d-flex justify-content-center">
                      <a
                        data-bs-toggle="tooltip"
                        data-bs-placement="top"
                        href="{% url 'projection_parameter' item.pk %}"
                        class="btn btn-sm btn-outline-safa me-2 px-3"
                        title="Editar Parametro"
                      > <i class="bi bi-pencil-square"></i>
                      </a>
                    </div>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="6" class="text-center fs-5">No Data</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% include 'master_budget/shared/pagination_multiple.html' with qs=result %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
  $(document).ready(()=>{
    $('.select2-style').select2({
      language: "es",
      dropdownParent: $('#addProjectionModal')
    });
    $(
      "#id_period option[value= '{{request.GET.period}}'] "
    ).prop('selected', true).trigger("change");

    $('.delete-projection').click(function(){
      let url = $(this).data('url')
      if(!!url){
        $('#deleteProjectionForm').attr('action', url)
        $('#deleteProjectionModal').modal('show');
      }
    })
  })
</script>

<script>
  $(document).ready(()=>{
    $('#btnAddProjectionParameter').click(()=>{
      let url ='{% url "projection_parameters" %}'
      loaderShow(true)
      $.ajax({
        type: 'GET',
        data: {},
        url: url
      })
      .done((res)=>{
        fillSelect(res)
        $('#addProjectionModal').modal('show')
        loaderShow(false)
      })
      .fail(handleError)
    })
  
    const fillSelect = (resp) => {
      $(`#id_date_base`).empty();
      $(`#id_date_base`).append('<option value="">-- Seleccione Fecha Cierre Base --</option>');
      $.each(resp, (key, val) => {
        $(`#id_date_base`).append(`<option value='${val.id}'>${val.date}</option>`);
      })
      $(`#id_date_base`).trigger("chosen:updated");
    }


    const handleError = (e) => {
      console.log(e);
      loaderShow(false)
      alert("No se pudo cargar fechas cierres!")
    }
  })
</script>
{% endblock javascript %}