apps/master_budget/patrimony/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('scenarios/', views.scenarios_equity, name="scenarios_equity"),
    path('scenario/detail/<int:id>/', views.scenario_equity, name="scenario_equity"),
    path('surplus/', views.surplus, name="surplus"),
    path('surplus/detail/<int:id>/', views.surplus_detail, name="surplus_detail")
]

ppto_safa/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.conf.urls import (
    handler404,
    handler500,
    handler403
)

from apps.main.views import error_500, error_404, error_403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('administration/', include('apps.administration.urls')),
    path('security/', include('apps.security.urls')),
    path('expenses-budgets/', include('apps.expenses_budgets.urls')),
    path('travel-budgets/', include('apps.travel_budgets.urls')),
    path('investment-budgets/', include('apps.investment_budgets.urls')),
    path('staff-budgets/', include('apps.staff_budgets.urls')),
    path('indirect-budgets/', include('apps.indirect_budgets.urls')),
    path('income-budgets/', include('apps.income_budgets.urls')),
    path('cost-budgets/', include('apps.cost_budgets.urls')),
    path('goals/', include('apps.goals.urls')),
    path('master-budget/', include('apps.master_budget.urls')),
    path(
        'master-budget/loan-portfolio/',
        include('apps.master_budget.loan_portfolio.urls')
    ),
    path(
        'master-budget/passives/',
        include('apps.master_budget.passives.urls')
    ),
    path(
        'master-budget/non-performing-assets/',
        include('apps.master_budget.non_performing_assets.urls')
    ),
    path(
        'master-budget/payment-payroll/',
        include('apps.master_budget.payment_payroll.urls')
    ),
    path(
        'master-budget/equity/',
        include('apps.master_budget.patrimony.urls')
    ),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
) + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

handler403 = error_403  # NOQA
handler404 = error_404  # NOQA
handler500 = error_500  # NOQA

apps/master_budget/patrimony/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.main.models import Periodo

from apps.master_budget.models import (
    AuditDataMixin, AmountMonthlyMixin, AmountIncreasesMonthlyMixin,
    MasterParameters
)
from utils.constants import OTHERS_ASSETS_CRITERIA


def is_percentage(value):
    if value >= 0 and value <= 1:
        return True
    return False


class EquityCategory(AuditDataMixin):
    id = models.AutoField(primary_key=True, db_column="Id")
    name = models.CharField(null=True, blank=True, max_length=50, db_column="Nombre")
    is_active = models.BooleanField(null=True, blank=True, default=True, db_column="Estado")
    identifier = models.CharField(null=True, blank=True, max_length=150, db_column="Identificador")
    created_by = models.ForeignKey(User, models.DO_NOTHING, db_column="CreadoPor", null=True, blank=True) # NOQA
    updated_by = models.ForeignKey(
        User, models.DO_NOTHING, db_column="ActualizadoPor", null=True, blank=True,
        related_name="user_update_equity_category"
    )

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroPatrimonioCat"

    def __str__(self):
        return f"{self.name}"


class EquityScenario(AuditDataMixin):
    id = models.AutoField(primary_key=True, db_column='Id')
    period_id = models.ForeignKey(Periodo, models.DO_NOTHING, db_column="PeriodoId", null=True, blank=True) # NOQA
    parameter_id = models.ForeignKey(MasterParameters, models.DO_NOTHING, db_column="ParametroId")
    correlative = models.CharField(null=True, blank=True, max_length=50, db_column="Correlativo")
    comment = models.CharField(null=True, blank=True, max_length=500, db_column="Comentario")
    is_active = models.BooleanField(null=True, blank=True, default=True, db_column="Estado")
    deleted = models.BooleanField(null=True, blank=True, default=False, db_column="Eliminado")
    created_by = models.ForeignKey(User, models.DO_NOTHING, db_column="CreadoPor", null=True, blank=True) # NOQA
    updated_by = models.ForeignKey(
        User, models.DO_NOTHING, db_column="ActualizadoPor", null=True, blank=True,
        related_name="user_upd_equity_scenario"
    )

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroPatrimonioEsc"


class Equity(AuditDataMixin, AmountMonthlyMixin, AmountIncreasesMonthlyMixin):
    id = models.AutoField(primary_key=True, db_column="Id")
    scenario_id = models.ForeignKey(
        EquityScenario, models.DO_NOTHING, db_column="EscenarioId", null=True, blank=True
    )
    category_id = models.ForeignKey(
        EquityCategory, models.DO_NOTHING, db_column="CategoriaId", blank=True, null=True
    )
    category = models.IntegerField(db_column="Categoria", null=True, blank=True)
    category_name = models.CharField(db_column="CategoriaNombre", max_length=150, null=True, blank=True) # NOQA
    previous_balance = models.DecimalField(
        db_column="SaldoAnterior", decimal_places=2, max_digits=23, default=0, blank=True, null=True
    )
    criteria = models.IntegerField(db_column="Criterio", choices=OTHERS_ASSETS_CRITERIA, null=True, blank=True) # NOQA
    comment = models.CharField(db_column="Comentario", max_length=200, default='', null=True, blank=True) # NOQA
    percentage = models.FloatField(db_column="Procentaje", null=True, blank=True, default=0) # NOQA
    new_balance = models.DecimalField(
        db_column="NuevoSaldo", max_digits=23, decimal_places=2, default=0, blank=True, null=True
    )

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroPatrimonio"


class SurplusCategory(AuditDataMixin):
    id = models.AutoField(primary_key=True, db_column='Id')
    name = models.CharField(null=False, blank=False, max_length=100, db_column="Nombre")
    order = models.IntegerField(db_column="Orden", null=False, blank=False)
    action = models.CharField(null=False, blank=False, max_length=5, db_column="Accion")

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroCategoriaExcedentes"
        ordering = ('order',)

    def __str__(self):
        return self.name


class DistributionSurplusPeriod(AuditDataMixin):
    id = models.AutoField(primary_key=True, db_column='Id')
    period_id = models.ForeignKey(
        Periodo, models.DO_NOTHING, db_column="IdPeriodo", null=False, blank=False
    )
    surplus_amount = models.DecimalField(
        db_column="MontoExcedentes", decimal_places=2, max_digits=18, default=0, null=False,
        blank=False
    )

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroDistribucionExcedentesPeriodo"


class DistributionSurplusCategory(AuditDataMixin):
    id = models.AutoField(primary_key=True, db_column='Id')
    id_surplus_category = models.ForeignKey(
        SurplusCategory, models.DO_NOTHING, db_column="IdCategoriaExcedentes", null=False,
        blank=False
    )
    id_dsp = models.ForeignKey(
        DistributionSurplusPeriod, models.DO_NOTHING, db_column="IdDEP", null=False, blank=False
    )
    title = models.CharField(db_column="Etiqueta", null=False, blank=False, max_length=100)
    percentage = models.FloatField(
       db_column="Porcentaje", null=False, blank=False, default=0,
       validators=[is_percentage]
    )
    amount = models.DecimalField(
        db_column="Monto", decimal_places=2, max_digits=18, default=0, blank=False, null=False
    )

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroDistribucionExcedentesCategoria"

apps/master_budget/patrimony/views.py
from decimal import Decimal as dc
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.db.models import Sum

from apps.master_budget.models import MasterParameters
from apps.master_budget.patrimony import forms
from apps.master_budget.patrimony.request_get import QueryGetParms
from apps.master_budget.patrimony.request_post import equity_monthly_amount_clean
from apps.master_budget.patrimony.models import (
    EquityCategory,
    EquityScenario,
    Equity,
    DistributionSurplusPeriod,
    DistributionSurplusCategory,
    SurplusCategory,
)
from utils.constants import STATUS_SCENARIO, OTHERS_ASSETS_CRITERIA
from utils.sql import execute_sql_query
from utils.pagination import pagination


@login_required()
@permission_required('ppto_maestro.puede_listar_escenarios_patrimonio', raise_exception=True)
def scenarios_equity(request):
    form = forms.EquityScenarioForm()

    def _correlative(period, total):
        return f"ESC-{period}-{total}"

    if request.POST:
        if request.POST.get("method") == "create":
            if not request.user.has_perm('ppto_maestro.puede_crear_escenarios_patrimonio'):
                raise PermissionDenied
            form = forms.EquityScenarioForm(request.POST)
            if not form.is_valid():
                messages.warning(
                    request, f"Formulario no válido: {form.errors.as_text()}"
                )
            else:
                if request.POST.get("is_active") == "True":
                    EquityScenario.objects.filter(
                        parameter_id=request.POST.get("parameter_id")
                    ).update(is_active=False)
                _new = form.save()
                _new.period_id = _new.parameter_id.period_id
                _new.created_by = request.user
                _new.updated_by = request.user
                _new.save()
                _new.correlative = _correlative(
                    _new.parameter_id.period_id.descperiodo,
                    EquityScenario.objects.filter(period_id=_new.period_id).count(),
                )
                _new.save()
                messages.success(request, "Escenario creado con éxito!")
                for qs_category in EquityCategory.objects.filter(is_active=True):
                    query = f"{qs_category.identifier} '{_new.parameter_id.pk}'"
                    result = execute_sql_query(query)
                    if result.get("status") == "ok":
                        for item in result.get("data"):
                            Equity.objects.create(
                                scenario_id=_new,
                                category_id=qs_category,
                                category=item.get("CategoriaId", 0),
                                category_name=item.get("Categoria", ""),
                                previous_balance=item.get("Saldo", 0),
                                percentage=0,
                                new_balance=0,
                                amount_january=item.get("Saldo", 0),
                                amount_february=item.get("Saldo", 0),
                                amount_march=item.get("Saldo", 0),
                                amount_april=item.get("Saldo", 0),
                                amount_may=item.get("Saldo", 0),
                                amount_june=item.get("Saldo", 0),
                                amount_july=item.get("Saldo", 0),
                                amount_august=item.get("Saldo", 0),
                                amount_september=item.get("Saldo", 0),
                                amount_october=item.get("Saldo", 0),
                                amount_november=item.get("Saldo", 0),
                                amount_december=item.get("Saldo", 0),
                            )
                    else:
                        messages.danger(
                            request,
                            f"No se pudo extraer información Historica de categoria: {qs_category}",  # NOQA
                        )
                redirect_url = reverse("scenario_equity", kwargs={"id": _new.pk})
                full_redirect_url = f"{redirect_url}?option="
                return redirect(full_redirect_url)
        elif request.POST.get("method") == "clone":
            if not request.user.has_perm('ppto_maestro.puede_editar_escenarios_patrimonio'):
                raise PermissionDenied
            id = request.POST.get("id")
            comment = request.POST.get("comment")
            is_active = request.POST.get("is_active")
            qs_old_esc = get_object_or_404(EquityScenario, pk=id)
            _clone = EquityScenario.objects.get(pk=id)
            _clone.pk = None
            _clone.save()
            if is_active == "True":
                EquityScenario.objects.filter(
                    parameter_id=_clone.parameter_id.pk
                ).update(is_active=False)
            _clone.comment = comment
            _clone.is_active = is_active
            _clone.created_by = request.user
            _clone.updated_by = request.user
            _clone.correlative = _correlative(
                _clone.parameter_id.period_id.descperiodo,
                EquityScenario.objects.filter(period_id=_clone.period_id).count(),
            )
            _clone.save()
            _clone.refresh_from_db()
            for item_category in Equity.objects.filter(scenario_id=qs_old_esc.pk):
                _new = Equity.objects.get(pk=item_category.pk)
                _new.pk = None
                _new.save()
                _new.scenario_id = _clone
                _new.save()
            messages.success(request, "Escenario clonado con éxito!")
            redirect_url = reverse("scenario_equity", kwargs={"id": _clone.pk})
            full_redirect_url = f"{redirect_url}?option="
            return redirect(full_redirect_url)

    query_parms = QueryGetParms(request.GET)
    filters = query_parms.get_query_filters()
    qs = (
        EquityScenario.objects.filter(**filters)
        .exclude(deleted=True)
        .order_by("-parameter_id__is_active", "correlative")
    )
    parameters = MasterParameters.objects.filter(is_active=True).order_by(
        "-is_active", "period_id"
    )
    result = pagination(qs, page=query_parms.get_page())
    ctx = {
        "parameters": parameters,
        "status": STATUS_SCENARIO,
        "result": result,
        "form": form,
    }
    return render(request, "equity/scenarios.html", ctx)


@login_required()
@permission_required('ppto_maestro.puede_editar_escenarios_patrimonio', raise_exception=True)
def scenario_equity(request, id):
    qs = get_object_or_404(EquityScenario, pk=id)
    if request.method == "POST":
        if request.POST.get("method") == "criteria":
            item = get_object_or_404(Equity, pk=request.POST.get("pk"))
            item.comment = request.POST.get("comment", "")
            item.percentage = request.POST.get("percentage").replace(",", "")
            item.new_balance = request.POST.get("new_balance").replace(",", "")
            item.criteria = request.POST.get("criteria")
            item.save()
            messages.success(request, "Actualización realizada con éxito!")
        elif request.POST.get("method") == "define-monthly-by-amount":
            qs_item = get_object_or_404(Equity, pk=request.POST.get("pk"))
            data = equity_monthly_amount_clean(request.POST)
            form = forms.EquityDefineAmountMonthlyForm(data, instance=qs_item)
            if not form.is_valid():
                messages.warning(
                    request, f"Formulario no válido: {form.errors.as_text()}"
                )
            else:
                Equity.objects.filter(pk=qs_item.pk).update(**form.cleaned_data)
                messages.success(request, "Actualización realizada con éxito!")
        elif request.POST.get("method") == "change-status":
            if not qs.is_active:
                EquityScenario.objects.filter(parameter_id=qs.parameter_id.pk).update(
                    is_active=False
                )
            qs.is_active = not qs.is_active
            qs.save()
            message = (
                f"Escenario actualizado a : "
                f'{"Principal" if qs.is_active else "Secundario"}'
                f" con éxito!!"
            )
            messages.success(request, message)
        elif request.POST.get("method") == "delete":
            qs.is_active = False
            qs.deleted = True
            qs.updated_by = request.user
            qs.save()
            messages.error(request, "Escenario eliminado")
            return redirect("scenarios_others_passives")

    qs_details = Equity.objects.filter(scenario_id=qs.pk).order_by(
        "category_id", "category"
    )
    ctx = {
        "qs": qs,
        "qs_details": qs_details,
        "others_assets_criteria": OTHERS_ASSETS_CRITERIA,
        "form_clone": forms.ScenarioCloneForm(),
    }
    return render(request, "equity/scenario.html", ctx)


@login_required()
@permission_required('ppto_maestro.puede_listar_escenarios_distribucion_excedentes', raise_exception=True) # NOQA
def surplus(request):
    page = request.GET.get("page", 1)
    qs = DistributionSurplusPeriod.objects.all()
    qs_surplus = pagination(qs, page)
    ctx = {"qs_surplus": qs_surplus}
    return render(request, "surplus/surplus.html", ctx)


@login_required()
@permission_required('ppto_maestro.puede_editar_escenarios_distribucion_excedentes', raise_exception=True) # NOQA
def surplus_detail(request, id):
    qs = get_object_or_404(DistributionSurplusPeriod, pk=id)
    form = forms.DistributionSurplusCategoryForm()
    qs_categories = SurplusCategory.objects.all()

apps/master_budget/patrimony/templates/equity/scenario.html
{% extends 'master_budget/layout/base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Escenario Patrimonio{% endblock title %}

{% block breadcrumb %} 
  <li class="breadcrumb-item text-white ">
    <a href="{% url 'scenarios_equity' %}" class="text-white text-decoration-none">/ Patrimonio - Escenarios</a>
  </li>
  <li class="breadcrumb-item active text-white before-none" aria-current="page"> / Correlativo: {{qs.correlative}}</li>
{% endblock breadcrumb %}

{% block content %}
{% include 'equity/scenario_change_status.html' %}
{% include 'equity/scenario_clone.html' %}
{% include 'equity/scenario_delete.html' %}
{% include 'equity/scenario_modal_add_monthly_amount.html' %}
{% include 'equity/scenario_edit_criteria.html' %}
<div class="container-fluid mt-1">
  <div class="card card-template">
    <div class="card-header">
      <div class="row">
        <div class="col-md-5">
          <h5
            class="card-title fw-light fs-5"
            data-bs-toggle="tooltip"
            data-bs-placement="top"
            title="{{qs.comment}}"
            >Fecha Cierre {{qs.parameter_id}}
          </h5>
        </div>
        <div class="col-md-7">
          <div class="d-grid gap-2 d-flex justify-content-end">
            <button
              id="openModalChangeScenario"
              type="button"
              class="btn btn-outline-dark btn-sm float-end"
              data-url="{% url 'scenario_equity' qs.pk %}"
              data-text="{{qs.is_active|yesno:'Secundario,Principal'}}"
            >
            {{qs.is_active|yesno:'Mover a Secundario, Mover a Principal'}}
            </button>
            <button
              id="openModalDeleteScenario"
              type="button" 
              data-url="{% url 'scenario_equity' qs.pk %}"
              class="btn btn-outline-dark btn-sm float-end"
            >Eliminar
            </button>
            <button type="button" class="btn btn-outline-danger btn-sm float-end" id="openModalCloneScenario">Clonar</button>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      {% include 'equity/scenario_table_detail.html' %}
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
  <script>
    $(document).ready(()=>{
      const Locales = { maximumFractionDigits: 2}
      const numberLocale = (value) => new Intl.NumberFormat('en-US', Locales).format(value)
      const convertDecimalToPercentage = (value)=> numberLocale(parseFloat(value) * 100)

      const calculateTotalAmount = () =>{
        let sumTotal = 0;
        $('.amount-monthly').each( (index, elem) => sumTotal += parseFloat($(elem).val().replaceAll(',', '')))
        $('#idIncreases').html(numberLocale(sumTotal))
        const previousBalance = parseFloat($('#idPreviousBalance').text().replaceAll(',', ''))
        const newBalance = parseFloat($('#idNewBalance').text().replaceAll(',', ''))
        const difference = newBalance - (sumTotal + previousBalance)
        $('#idDiference').html(numberLocale(difference))
      }


      $('.add_criteria').click(function(){
        let pk = $(this).data('pk')
        let criteria = $(this).data('criteria')
        let comment = $(this).data('comment')
        let categoryName = $(this).data('category-name')
        let previousBalanceCommas = $(this).data('previous-balance-commas')
        let previousBalance = $(this).data('previous-balance')
        let percentage = $(this).data('percentage')
        let newBalance = $(this).data('new-balance')
        let newBalanceCommas = $(this).data('new-balance-commas')
        $('#id_pk_criteria').val(pk)
        $(`#id_criteria option[value= '${criteria}']`).prop('selected', true).trigger("change");
        $('#id_comment_criteria').val(comment)
        $('#id_criteria_percentage').val(percentage)
        $('#id_criteria_new_balance').val(newBalanceCommas)

        // Hidden
        $('#id_criteria_previous_balance_hidden').val(previousBalance)
        $('#id_criteria_new_balance_hidden').val(newBalance)

        $('#title_criteria').text(`Editar ${ categoryName }. | Saldo Anterior ${previousBalanceCommas}`)
        $('#editCriteriaScenarioModal').modal('show');
      })

      $(document).on('change', '#id_criteria', function(){
        let value = $(this).val()
        if(!!value === false) return
        $('#id_criteria_percentage').removeAttr('readonly')
        $('#id_criteria_new_balance').removeAttr('readonly')

        if(value === '1'){
          let previousValue = $('#id_criteria_previous_balance_hidden').val()
          $('#id_criteria_new_balance').val( numberWithCommas(previousValue) )
          $('#id_criteria_percentage').val( numberWithCommas( parseFloat(0).toFixed(2)) )
          $('#id_criteria_percentage').attr('readonly', true)
          $('#id_criteria_new_balance').attr('readonly', true)
        }else if(value === '2' || value === '3'){
          $('#id_criteria_new_balance').val( numberWithCommas( parseFloat(0).toFixed(2)) )
          $('#id_criteria_percentage').val( numberWithCommas( parseFloat(0).toFixed(2)) )
          $('#id_criteria_new_balance').attr('readonly', true) 
        }else if(value === '4'){
          $('#id_criteria_new_balance').val( numberWithCommas( parseFloat(0).toFixed(2)) )
          $('#id_criteria_percentage').val( numberWithCommas( parseFloat(0).toFixed(2)) )
          $('#id_criteria_percentage').attr('readonly', true) 
        }
      })

      $(document).on('keyup', '#id_criteria_percentage', function(){
        let percentage = $(this).val()
        let criteria = $('#id_criteria').val()
        let previousValue = $('#id_criteria_previous_balance_hidden').val()
        percentage = parseFloat(percentage)
        previousValue = parseFloat(previousValue)

        if(criteria === '2'){
          let result = (Math.abs(percentage) / 100) * previousValue
          result = previousValue + result
          if (!!result === false) result = 0
          $('#id_criteria_new_balance').removeAttr('readonly')
          $('#id_criteria_new_balance').val( numberWithCommas( parseFloat(result).toFixed(2)))
          $('#id_criteria_new_balance').attr('readonly', true) 
        }else if(criteria === '3'){
          let result = (Math.abs(percentage) / 100) * previousValue
          result = previousValue - result
          if (!!result === false) result = 0
          $('#id_criteria_new_balance').val( numberWithCommas( parseFloat(result).toFixed(2)))
          $('#id_criteria_new_balance').attr('readonly', true) 
        }
      })

      $('.add_monthly_amount').on('click', function(){
        $('#inputPkMonthlyAmount').val($(this).data('pk'))

        $('#accountNameDefineMonthlyAmount').html($(this).data('category-name'))
        $('#newAnnualAmountDefineMonthlyAmount').html(new Intl.NumberFormat().format($(this).data('new-balance')))
        $('#editMonthlyAmountDefinitionModal').modal('show');

        $('#id_define_monthly_amount_january').text(numberLocale($(this).data('amount_january')))
        $('#id_define_monthly_amount_february').text(numberLocale($(this).data('amount_february')))
        $('#id_define_monthly_amount_march').text(numberLocale($(this).data('amount_march')))
        $('#id_define_monthly_amount_april').text(numberLocale($(this).data('amount_april')))
        $('#id_define_monthly_amount_may').text(numberLocale($(this).data('amount_may')))
        $('#id_define_monthly_amount_june').text(numberLocale($(this).data('amount_june')))
        $('#id_define_monthly_amount_july').text(numberLocale($(this).data('amount_july')))
        $('#id_define_monthly_amount_august').text(numberLocale($(this).data('amount_august')))
        $('#id_define_monthly_amount_september').text(numberLocale($(this).data('amount_september')))
        $('#id_define_monthly_amount_october').text(numberLocale($(this).data('amount_october')))
        $('#id_define_monthly_amount_november').text(numberLocale($(this).data('amount_november')))
        $('#id_define_monthly_amount_december').text(numberLocale($(this).data('amount_december')))

        $('#id_define_monthly_increases_january').val(numberLocale($(this).data('increases_january')))
        $('#id_define_monthly_increases_february').val(numberLocale($(this).data('increases_february')))
        $('#id_define_monthly_increases_march').val(numberLocale($(this).data('increases_march')))
        $('#id_define_monthly_increases_april').val(numberLocale($(this).data('increases_april')))
        $('#id_define_monthly_increases_may').val(numberLocale($(this).data('increases_may')))
        $('#id_define_monthly_increases_june').val(numberLocale($(this).data('increases_june')))
        $('#id_define_monthly_increases_july').val(numberLocale($(this).data('increases_july')))
        $('#id_define_monthly_increases_august').val(numberLocale($(this).data('increases_august')))
        $('#id_define_monthly_increases_september').val(numberLocale($(this).data('increases_september')))
        $('#id_define_monthly_increases_october').val(numberLocale($(this).data('increases_october')))
        $('#id_define_monthly_increases_november').val(numberLocale($(this).data('increases_november')))
        $('#id_define_monthly_increases_december').val(numberLocale($(this).data('increases_december')))
        $('#idPreviousBalance').text(numberLocale($(this).data('previous-balance')))
        $('#idNewBalance').text(numberLocale($(this).data('new-balance')))

        calculateTotalAmount()
      })
      $(document).on('click', '.editMonthlyAmount', function(){
        let method = $(this).data('method');
        const defineMonthlyByAmount = 'define-monthly-by-amount';
        const defineMonthlyByPercentage = 'define-monthly-by-percentage';

        if($(this).data('method') === defineMonthlyByAmount){
          changeInputAmountEditStatus(false)
          changeInputPercentageEditStatus(true)
          $('#btnDefineMonthlyAmount').removeClass('btn-outline-secondary').addClass('btn-success')
          $('#btnDefineMonthlyPercentage').removeClass('btn-success').addClass('btn-outline-secondary')
          $('#inputMethodMonthlyAmount').val(defineMonthlyByAmount)
        }else{
          changeInputAmountEditStatus(true);
          changeInputPercentageEditStatus(false);
          $('#btnDefineMonthlyAmount').removeClass('btn-success').addClass('btn-outline-secondary')
          $('#btnDefineMonthlyPercentage').removeClass('btn-outline-secondary').addClass('btn-success')
          $('#inputMethodMonthlyAmount').val(defineMonthlyByPercentage)
        }
      })
      
      $(document).on('change', '.amount-monthly', calculateTotalAmount)
    })
  </script>

  <!-- Modals Scripts -->
  <script>
    $(document).ready(()=>{
      $('.select2-style').select2({
        language: "es",
        dropdownParent: $('#cloneScenarioModal')
      });


      $('#openModalCloneScenario').click(()=> $('#cloneScenarioModal').modal('show'))
      $('#openModalChangeScenario').click(()=> {
        let url = $('#openModalChangeScenario').data('url')
        let text = $('#openModalChangeScenario').data('text')
        $('#formChangeStatusScenario').attr('action', url);
        $('#textChangeStatus').html(`¿Desea mover escenario a ${text}?`)
        $('#changeStatusScenarioModal').modal('show')
      })
      $('#openModalDeleteScenario').click(()=> {
        let url = $('#openModalDeleteScenario').data('url')
        $('#formDeleteScenario').attr('action', url);
        $('#textDelete').html(`¿Desea eliminar escenario?`)
        $('#deleteScenarioModal').modal('show')
      })
      
      $('#openModalGlobalScenario').click(()=>{
        $('#globalNonPerformingAssetsScenarioModal').modal('show')
      })
    })
  </script>
  <!-- End Modals Scripts -->

{% endblock javascript %}