apps/travel_budgets/urls.py
from django.urls import path
from apps.travel_budgets.views import (
    travel_budget_register,
    travel_budget_update,
    travel_budget_delete,
    generate_excel_report,
    check_out_travel,
    load_travel_distribution
)

urlpatterns = [
    path(
        'travel-budget-register/',
        travel_budget_register,
        name='travel_budget_register'
    ),
    path(
        'travel-budget-update/<int:id>/',
        travel_budget_update,
        name='travel_budget_update'
    ),
    path(
        'travel-budget-delete/<int:id>/',
        travel_budget_delete,
        name='travel_budget_delete'
    ),
    path(
        'generate-excel-report/<int:period>/<int:cost_center>/',
        generate_excel_report,
        name='generate_excel_report'
    ),
    path(
        'check-out/',
        check_out_travel,
        name='check_out_travel'
    ),
    path(
        'load-travel-distribution/',
        load_travel_distribution,
        name='load_travel_distribution'
    ),
]

ppto_safa/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.conf.urls import (
    handler404,
    handler500,
    handler403
)

from apps.main.views import error_500, error_404, error_403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('administration/', include('apps.administration.urls')),
    path('security/', include('apps.security.urls')),
    path('expenses-budgets/', include('apps.expenses_budgets.urls')),
    path('travel-budgets/', include('apps.travel_budgets.urls')),
    path('investment-budgets/', include('apps.investment_budgets.urls')),
    path('staff-budgets/', include('apps.staff_budgets.urls')),
    path('indirect-budgets/', include('apps.indirect_budgets.urls')),
    path('income-budgets/', include('apps.income_budgets.urls')),
    path('cost-budgets/', include('apps.cost_budgets.urls')),
    path('goals/', include('apps.goals.urls')),
    path('master-budget/', include('apps.master_budget.urls')),
    path(
        'master-budget/loan-portfolio/',
        include('apps.master_budget.loan_portfolio.urls')
    ),
    path(
        'master-budget/passives/',
        include('apps.master_budget.passives.urls')
    ),
    path(
        'master-budget/non-performing-assets/',
        include('apps.master_budget.non_performing_assets.urls')
    ),
    path(
        'master-budget/payment-payroll/',
        include('apps.master_budget.payment_payroll.urls')
    ),
    path(
        'master-budget/equity/',
        include('apps.master_budget.patrimony.urls')
    ),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
) + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

handler403 = error_403  # NOQA
handler404 = error_404  # NOQA
handler500 = error_500  # NOQA

apps/travel_budgets/forms.py
from django import forms

from utils.constants import TRAVEL_TYPE, TRAVEL_CATEGORY, ZONES


class NacionalTravelBudget(forms.Form):
    category = forms.CharField(
        required=True,
        error_messages={'required': 'Por favor seleccione categoria'},
    )
    filial = forms.CharField(
        required=True,
        error_messages={'required': 'Por favor seleccione filial'}
    )
    cost_center = forms.CharField(
        required=True,
        error_messages={'required': 'Por favor seleccione centro de costo'}
    )
    period = forms.IntegerField(
        required=True,
        min_value=1,
        error_messages={'required': 'Por favor seleccione periodo'}
    )
    travel_type = forms.CharField(
        required=True,
        error_messages={'required': 'Por favor ingrese/seleccione tipo de viatico'}
    )
    number_trips = forms.IntegerField(
        required=True,
        error_messages={'required': 'Por favor ingrese cantidad de viaje'}
    )
    number_days = forms.FloatField(
        required=True,
        error_messages={'required': 'Por favor ingrese cantidad de dias'}
    )
    justification = forms.CharField(
        required=True,
        error_messages={'required': 'Por favor ingrese justificacion'}
    )

    class Meta:
        fields = '__all__'

    def clean_travel_type(self):
        cleaned = self.cleaned_data['travel_type']
        travel_type = TRAVEL_TYPE.get(int(cleaned), None)
        if travel_type is None:
            raise forms.ValidationError("Tipo de viaje no reconocido")
        return cleaned

    def clean_category(self):
        cleaned = self.cleaned_data['category']
        category = TRAVEL_CATEGORY.get(cleaned, None)
        if category is None:
            raise forms.ValidationError("Categoria no reconocida")
        return cleaned


class InternacionalTravelBudget(forms.Form):
    category = forms.CharField(
        required=True,
        error_messages={'required': 'Por favor seleccione categoria'},
    )
    zone = forms.CharField(
        required=True,
        error_messages={'required': 'Por favor seleccione zone'}
    )
    cost_center = forms.CharField(
        required=True,
        error_messages={'required': 'Por favor seleccione centro de costo'}
    )
    period = forms.IntegerField(
        required=True,
        min_value=1,
        error_messages={'required': 'Por favor seleccione periodo'}
    )
    travel_type = forms.CharField(
        required=True,
        error_messages={'required': 'Por favor ingrese/seleccione tipo de viatico'}
    )
    number_trips = forms.IntegerField(
        required=True,
        error_messages={'required': 'Por favor ingrese cantidad de viaje'}
    )
    number_days = forms.FloatField(
        required=True,
        error_messages={'required': 'Por favor ingrese cantidad de dias'}
    )
    justification = forms.CharField(
        required=True,
        error_messages={'required': 'Por favor ingrese justificacion'}
    )

    class Meta:
        fields = '__all__'

    def clean_travel_type(self):
        cleaned = self.cleaned_data['travel_type']
        travel_type = TRAVEL_TYPE.get(int(cleaned), None)
        if travel_type is None:
            raise forms.ValidationError("Tipo de viaje no reconocido")
        return cleaned

    def clean_category(self):
        cleaned = self.cleaned_data['category']
        category = TRAVEL_CATEGORY.get(cleaned, None)
        if category is None:
            raise forms.ValidationError("Categoria no reconocida")
        return cleaned

    def clean_zone(self):
        cleaned = self.cleaned_data['zone']
        zone = ZONES.get(cleaned, None)
        if zone is None:
            raise forms.ValidationError("Zona no reconocida")
        return cleaned

apps/travel_budgets/views.py
import datetime as dt
import json

from django.shortcuts import (
    render,
    redirect,
    get_object_or_404
)
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.db.models import Q, Sum

from apps.main.models import (
    Centroscosto,
    Detallexpresupuestoviaticos,
    Filiales,
    Periodo,
    ResponsablesPorCentrosCostos,
    Manejodeviaticos,
    Transaccionesviaticos
)
from apps.travel_budgets.forms import (
    InternacionalTravelBudget,
    NacionalTravelBudget
)
from utils.constants import TRAVEL_CATEGORY, ZONES
from utils.pagination import pagination
from apps.travel_budgets.reports import (
    create_excel_report,
    generate_excel_file_format_distribution,
    load_excel_file
)


@login_required()
def travel_budget_register(request):
    if (
        not request.user.has_perm('ppto_viaticos.puede_ingresar_ppto_viaticos_todos') and
        not request.user.has_perm('ppto_viaticos.puede_ingresar_ppto_viaticos')
    ):
        raise PermissionDenied

    def _get_ceco():
        if not request.user.has_perm('ppto_viaticos.puede_ingresar_ppto_viaticos_todos'):
            ceco_assigned = ResponsablesPorCentrosCostos.objects.filter(
                CodUser=request.user.pk, Estado=True
            ).values_list('CodCentroCosto', flat=True)
            return Centroscosto.objects.filter(habilitado=True).filter(
                pk__in=list(ceco_assigned)
            )
        else:
            return Centroscosto.objects.filter(habilitado=True)

    if request.method == 'POST':
        if request.POST.get('method') == 'filter-travel-budget':
            try:
                request.session['cost_center'] = request.POST.get('cost_center', '')
                request.session['period'] = request.POST.get('period', '')
                cost_center = request.POST.get('cost_center', '')
                period = request.POST.get('period', '')
                qs_national_travel_budget = Detallexpresupuestoviaticos.objects.filter(
                    codcentrocosto=cost_center,
                    tipoviatico=1,
                    habilitado=True,
                    codperiodo=period
                )
                qs_international_travel_budget = Detallexpresupuestoviaticos.objects.filter( # NOQA
                    codcentrocosto=cost_center,
                    tipoviatico=2,
                    habilitado=True,
                    codperiodo=period
                )
            except Exception as e:
                messages.warning(request, f'Exception cached: {e.__str__() }')
            else:
                periods = Periodo.objects.filter(habilitado=True)
                filials = Filiales.objects.all()
                ctx = {
                    'periods': periods,
                    'cost_centers': _get_ceco(),
                    'filials': filials,
                    'categories': TRAVEL_CATEGORY,
                    'zones': ZONES,
                    'qs_international_travel_budget': qs_international_travel_budget,
                    'qs_national_travel_budget': qs_national_travel_budget
                }
                return render(request, 'travel_budget_register.html', ctx)

        if request.POST.get('method') == 'create-international-travel-budget':
            try:
                form = InternacionalTravelBudget(request.POST)
                if not form.is_valid():
                    raise ValidationError(f'{ form.errors.as_text() }')
                if not Detallexpresupuestoviaticos.objects.filter(
                    categoria=form.cleaned_data.get('category'),
                    zona=form.cleaned_data.get('zone'),
                    codcentrocosto=form.cleaned_data.get('cost_center'),
                    usuariocreacion=request.user.pk,
                    codperiodo=form.cleaned_data.get('period'),
                    habilitado=True
                ).exists():
                    new_record = Detallexpresupuestoviaticos()
                    new_record.codperiodo = Periodo.objects.get(
                        pk=form.cleaned_data.get('period')
                    )
                    new_record.codcentrocosto = Centroscosto.objects.get(
                        pk=form.cleaned_data.get('cost_center')
                    )
                    new_record.zona = form.cleaned_data.get('zone')
                    new_record.categoria = form.cleaned_data.get('category')
                    new_record.tipoviatico = form.cleaned_data.get('travel_type')
                    new_record.cantidadviajes = form.cleaned_data.get('number_trips')
                    new_record.cantidaddias = form.cleaned_data.get('number_days')
                    new_record.justificacion = form.cleaned_data.get('justification')
                    new_record.usuariocreacion = request.user
                    new_record.fechacreacion = dt.datetime.today()
                    new_record.habilitado = True
                    new_record.save()
                    messages.success(
                        request,
                        'Presupuesto para viatico internacional registrado con éxito'
                    )
                else:
                    messages.warning(
                        request,
                        'Presupuesto para viatico internacional ya existe!'
                    )
            except (
                Filiales.DoesNotExist,
                Periodo.DoesNotExist,
                Centroscosto.DoesNotExist
            ) as e:
                messages.warning(
                    request,
                    f'No encontrado: {e.__str__()}'
                )
                return redirect('travel_budget_register')
            except ValidationError as e:
                messages.warning(
                    request,
                    f'Error de validacion de formulario: {e.__str__()}'
                )
                return redirect('travel_budget_register')
            except Exception as e:
                messages.error(
                    request,
                    f'Exception no determinada: {e.__str__()}'
                )
                return redirect('travel_budget_register')
            else:
                cost_center = request.POST.get('cost_center', '')
                period = request.POST.get('period', '')
                qs_national_travel_budget = Detallexpresupuestoviaticos.objects.filter(
                    codcentrocosto=cost_center,
                    tipoviatico=1,
                    habilitado=True,
                    codperiodo=period
                )
                qs_international_travel_budget = Detallexpresupuestoviaticos.objects.filter( # NOQA
                    codcentrocosto=cost_center,
                    tipoviatico=2,
                    habilitado=True,
                    codperiodo=period
                )
                periods = Periodo.objects.filter(habilitado=True)
                filials = Filiales.objects.all()
                ctx = {
                    'periods': periods,
                    'cost_centers': _get_ceco(),
                    'filials': filials,
                    'categories': TRAVEL_CATEGORY,
                    'zones': ZONES,
                    'qs_international_travel_budget': qs_international_travel_budget,
                    'qs_national_travel_budget': qs_national_travel_budget
                }
                return render(request, 'travel_budget_register.html', ctx)

        if request.POST.get('method') == 'create-national-travel-budget':
            try:
                form = NacionalTravelBudget(request.POST)
                if not form.is_valid():
                    raise ValidationError(f'{ form.errors.as_text() }')

                if not Detallexpresupuestoviaticos.objects.filter(
                    categoria=form.cleaned_data.get('category'),
                    filial=form.cleaned_data.get('filial'),
                    codcentrocosto=form.cleaned_data.get('cost_center'),
                    usuariocreacion=request.user.pk,
                    codperiodo=form.cleaned_data.get('period'),
                    habilitado=True
                ).exists():
                    new_record = Detallexpresupuestoviaticos()
                    new_record.codperiodo = Periodo.objects.get(
                        pk=form.cleaned_data.get('period')
                    )
                    new_record.filial = Filiales.objects.get(
                        pk=form.cleaned_data.get('filial')
                    )
                    new_record.categoria = form.cleaned_data.get('category')
                    new_record.tipoviatico = form.cleaned_data.get('travel_type')
                    new_record.cantidadviajes = form.cleaned_data.get('number_trips')
                    new_record.cantidaddias = form.cleaned_data.get('number_days')
                    new_record.codcentrocosto = Centroscosto.objects.get(
                        pk=form.cleaned_data.get('cost_center')
                    )
                    new_record.justificacion = form.cleaned_data.get('justification')
                    new_record.usuariocreacion = request.user
                    new_record.fechacreacion = dt.datetime.today()
                    new_record.habilitado = True
                    new_record.save()
                    messages.success(
                        request,
                        'Presupuesto para viatico nacional registrado con éxito'
                    )
                else:
                    messages.warning(
                        request,
                        'Presupuesto para viatico nacional ya existe!'
                    )
            except (
                Filiales.DoesNotExist,
                Periodo.DoesNotExist,

apps/travel_budgets/templates/travel_budget_form_filters.html
{% load static %}
{% load humanize %}
<h5 class="my-3 fw-light">Seleccione datos</h5>
<form
  method="post"
  accept-charset="utf-8"
  action="{% url 'travel_budget_register' %}"
>
  {% csrf_token %}
  <input type="hidden" name="method" value="filter-travel-budget" />
  <div class="row">
    <div class="col-md-4 mb-3">
      <div class="form-group">
        <label for="id_periods">Periodo</label>
        <select 
          class="form-select select2-style" 
          id="id_period" 
          name="period" 
          required
          style="width: 100%;"
        >
          <option value="">--- Seleccione Periodo ---</option>
          {% for period in periods %}
          <option value="{{period.pk}}">{{period}}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="w-100"></div>
    <div class="col-md-4 mb-3">
      <div class="form-group">
        <label for="id_cost_centers">Centro de Costos</label>
        <select 
          class="form-select select2-style"
          id="id_cost_center"
          name="cost_center"
          required
          style="width: 100%;"
        >
          <option value="">--- Seleccione Centro Costos ---</option>
          {% for cost_center in cost_centers %}
          <option value="{{cost_center.pk}}">{{cost_center}}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="w-100"></div>
    <div class="col-md-4">
      <div class="d-grid gap-2 my-2">
        <button class="btn btn-safa" type="submit">Filtrar</button>
      </div>
      <button 
        class="btn btn-outline-safa" 
        id="btn-generate-report" 
        type="button"
      >Generar Reporte
      </button>
    </div>
  </div>
</form>

apps/travel_budgets/templates/travel_budget_register.html
{% extends 'layout/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Presupuestos de Viaticos {% endblock title %}
{% block breadcrumb %}
  <li class="breadcrumb-item active text-white" aria-current="page">/ Ingreso de Presupuestos de Viaticos</li>
{% endblock breadcrumb %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/budgets.css' %}">
{% endblock css %}

{% block content %}
<div class="container-fluid pt-4">
  <div class="card card-template">
    <div class="card-body">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="filtros-tab" data-bs-toggle="tab" data-bs-target="#filtros" type="button"
            role="tab" aria-controls="filtros" aria-selected="true">Filtrar</button>
        </li>
        <li class="nav-item" role="presentation">
          <button
            class="nav-link"
            id="presupuestar-national-tab"
            data-bs-toggle="tab"
            data-bs-target="#presupuestar-national"
            type="button"
            role="tab"
            aria-controls="presupuestar-national"
            aria-selected="false"
          >Presupuestar Nacional</button>
        </li>
        <li class="nav-item" role="presentation">
          <button 
            class="nav-link"
            id="presupuestar-international-tab"
            data-bs-toggle="tab"
            data-bs-target="#presupuestar-international"
            type="button"
            role="tab"
            aria-controls="presupuestar-international"
            aria-selected="false"
          >Presupuestar Internacional</button>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="filtros" role="tabpanel" aria-labelledby="filtros-tab">
          {% include 'travel_budget_form_filters.html' %}
        </div>
        <div class="tab-pane fade" id="presupuestar-national" role="tabpanel" aria-labelledby="presupuestar-national-tab">
          {% include 'travel_budget_form_create_national_travel.html' %}
        </div>
        <div class="tab-pane fade" id="presupuestar-international" role="tabpanel" aria-labelledby="presupuestar-international-tab">
          {% include 'travel_budget_form_create_international_travel.html' %}
        </div>
      </div>
    </div>
  </div>
  
  {% include 'card_national_travel_budget.html' %}
  {% include 'card_international_travel_budget.html' %}

  <div class="modal fade" id="modalDelete" tabindex="-1" aria-labelledby="modalDeleteLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title fw-light" id="modalDeleteLabel">Eliminar Presupuesto </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post" id="formDelete">
          {% csrf_token %}
          <div class="modal-body">
            <h5 class="fw-light">Desea eliminar presupuesto?</h5>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-safa">Si, eliminar</button>
          </div>
        </form>
      </div>
    </div>
  </div>

</div>

{% endblock content %}

{% block javascript %}

<script>
  $(document).ready(()=>{
    $(document).on('click', '.delete-travel-budget', function(){
      $('#formDelete').attr('action', $(this).data('form-url'))
      $('#modalDelete').modal('show');
    })
  })
</script>

<script>
  $(document).ready(() => {
    $('#btn-generate-report').hide();
    $(
      "#id_period option[value= '{{request.session.period}}'] "
    ).prop('selected', true).trigger("change");
    $(
      "#id_cost_center option[value= '{{request.session.cost_center}}'] "
    ).prop('selected', true).trigger("change");

    $(
      "#id_period_2 option[value= '{{request.session.period}}'] "
    ).prop('selected', true).trigger("change");
    $(
      "#id_cost_center_2 option[value= '{{request.session.cost_center}}'] "
    ).prop('selected', true).trigger("change");
    $(
      "#id_period_3 option[value= '{{request.session.period}}'] "
    ).prop('selected', true).trigger("change");
    $(
      "#id_cost_center_3 option[value= '{{request.session.cost_center}}'] "
    ).prop('selected', true).trigger("change");

    $('#id_period, #id_cost_center').change(() => {
      if ( $('#id_period').val().trim() !== '' && $('#id_cost_center').val().trim() !== '') {
        $('#btn-generate-report').show();
      }
    });


    setTimeout(() => {
      if ( $('#id_period').val().trim() !== '' && $('#id_cost_center').val().trim() !== '') {
        $('#btn-generate-report').show();
      }
    }, 2000);
  })
</script>
<script>
  $('#btn-generate-report').click((e) => {
    e.stopPropagation()
    e.preventDefault();
    let cost_center = $('#id_cost_center').val();
    let period = $('#id_period').val();
    if (cost_center === '') alert("Seleccione Centro de costo para generar reporte")
    else if (period === '') alert("Seleccione Periodo para generar reporte")
    else {
      let url = `/travel-budgets/generate-excel-report/${period}/${cost_center}/`
      window.open(url, '_blank').focus();
    }
  })
</script>
{% endblock javascript %}

apps/travel_budgets/templates/travel_budget_update.html
{% extends 'layout/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Presupuestos de Viaticos {% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/budgets.css' %}">
{% endblock css %}

{% block breadcrumb %}
<li class="breadcrumb-item text-white ">
  <a href="{% url 'travel_budget_register' %}" class="text-white text-decoration-none">/ Listado Viaticos</a>
</li>
<li class="breadcrumb-item active text-white before-none" aria-current="page"> / Editar Viatico</li>
{% endblock breadcrumb %}

{% block content %}
<div class="container-fluid pt-2">

  <div class="card card-template">
    <div class="card-header">
      <h5 class="card-title fw-light">Editar Presupuestos de Viaticos</h5>
    </div>
    <div class="card-body">
      <form
        method="post"
        accept-charset="utf-8"
        action="{% url 'travel_budget_update' qs.pk %}"
      >
        {% csrf_token %}
        <input type="hidden" name="travel_type" value="{{qs.tipoviatico}}" />
        <input 
          type="hidden" 
          name="method" 
          {% if qs.tipoviatico == 1 %}
            value="update-national-travel-budget"
          {% else %} 
            value="update-international-travel-budget"
          {% endif %}
        />
        <div class="row">
          <div class="col-md-4 mb-3">
            <div class="form-group">
              <label for="id_period">Periodo</label>
              <select 
                class="form-select select2-style" 
                id="id_period" 
                name="period" 
                required
                style="width: 100%;"
              >
                <option value="">--- Seleccione Periodo ---</option>
                {% for period in periods %}
                <option 
                  value="{{period.pk}}"
                  {% if period.pk == qs.codperiodo.pk %} selected {% endif %}
                >{{period}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <div class="form-group">
              <label for="id_cost_center_2">Centro de Costos</label>
              <select 
                class="form-select select2-style"
                id="id_cost_center_2"
                name="cost_center"
                required
                style="width: 100%;"
              >
                <option value="">--- Seleccione Centro Costos ---</option>
                {% for cost_center in cost_centers %}
                <option 
                  value="{{cost_center.pk}}"
                  {% if cost_center.pk == qs.codcentrocosto.pk %} selected {% endif %}
                >{{cost_center}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <div class="form-group">
              <label for="id_number_trips_national">Cantidad de viajes</label>
              <input
                class="form-control" 
                type="number"
                name="number_trips"
                required
                value="{{qs.cantidadviajes}}"
                id="id_number_trips_national"
              />
            </div>
          </div>
          <div class="w-100"></div>
          <div class="col-md-4 mb-3">
            <div class="form-group">
              <label for="id_category_national">Categoria</label>
              <select 
                class="form-select select2-style"
                id="id_category_national"
                name="category" 
                required
                style="width: 100%;"
              >
                <option value="">--- Seleccione categoria ---</option>
                {% for key, category in categories.items %}
                <option 
                  value="{{key}}" 
                  {% if key == qs.categoria %} selected {% endif %}
                >{{category}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          {% if qs.tipoviatico == 1 %}
          <div class="col-md-4 mb-3">
            <div class="form-group">
              <label for="id_filial_national">Filiales</label>
              <select 
                class="form-select select2-style"
                id="id_filial_national"
                name="filial" 
                required
                style="width: 100%;"
              >
                <option value="">--- Seleccione filial ---</option>
                {% for filial in filials %}
                <option 
                  value="{{filial.pk}}"
                  {% if filial.pk == qs.filial.pk %} selected {% endif %}
                >{{filial}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          {% else %}
          <div class="col-md-4 mb-3">
            <div class="form-group">
              <label for="id_zone">Zona</label>
              <select 
                class="form-select select2-style"
                id="id_zone"
                name="zone" 
                required
                style="width: 100%;"
              >
                <option value="">--- Seleccione zone ---</option>
                {% for key, zone in zones.items %}
                <option 
                  value="{{key}}"
                  {% if key == qs.zona %} selected {% endif %}
                >{{zone}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          {% endif %}
          <div class="col-md-4 mb-3">
            <div class="form-group">
              <label for="id_number_days_national">Cantidad de días</label>
              <input
                class="form-control" 
                type="number"
                step="any"
                name="number_days"
                required
                value='{{qs.cantidaddias|floatformat:2}}'
                id="id_number_days_national"
              />
            </div>
          </div>
          <div class="w-100"></div>

          <div class="col-md-4 mb-3">
            <label for="id_justification_national">Justificación</label>
            <textarea
              name="justification"
              required
              class="form-control"
              id="id_justification_national"
              rows="3"
              style="resize: none;"
              >{{qs.justificacion|default:''}}</textarea>
          </div>
          <div class="w-100"></div>
          <div class="col-md-4">
            <div class="d-grid gap-2 my-2">
              <button class="btn btn-safa" type="submit">Guardar</button>
            </div>
          </div>
        </div>
      </form>

    </div>
  </div>

</div>
{% endblock content %}

{% block javascript %}
<script>
  $(document).ready(() => {
    $('#btn-generate-report').hide();
  })
</script>
{% endblock javascript %}