apps/master_budget/passives/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        'savings-liabilities/scenarios/',
        views.scenarios_savings_liabilities,
        name="scenarios_savings_liabilities"
    ),
    path(
        'savings-liabilities/scenario/detail/<int:id>/',
        views.scenario_savings_liabilities,
        name="scenario_savings_liabilities"
    ),
    path(
        'savings-liabilities/scenario/detail/comments/<int:id>/',
        views.scenario_savings_liabilities_comments,
        name="scenario_savings_liabilities_comments"
    ),
    path(
        'liabilities-loans/scenarios/',
        views.scenarios_liabilities_loans,
        name="scenarios_liabilities_loans"
    ),
    path(
        'liabilities-loans/scenario/detail/<int:id>/',
        views.scenario_liabilities_loans,
        name="scenario_liabilities_loans"
    ),
    path(
        'liabilities-loans/scenario/detail/comments/<int:id>/',
        views.scenario_liabilities_loans_comments,
        name="scenario_liabilities_loans_comments"
    ),
    path(
        'others-passives/scenarios/', views.scenarios_others_passives, name="scenarios_others_passives" # NOQA
    ),
    path(
        'others-passives/scenario/detail/<int:id>/',
        views.scenario_others_passives,
        name="scenario_others_passives"
    ),
]

apps/master_budget/patrimony/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('scenarios/', views.scenarios_equity, name="scenarios_equity"),
    path('scenario/detail/<int:id>/', views.scenario_equity, name="scenario_equity"),
    path('surplus/', views.surplus, name="surplus"),
    path('surplus/detail/<int:id>/', views.surplus_detail, name="surplus_detail")
]

apps/master_budget/urls.py
from django.urls import path
from apps.master_budget.views import (
    master_budget_dashboard,
    projection_parameters,
    projection_parameter,
    profit_loss_report_complementary_projection,
    profit_loss_report_complementary_projection_detail
)

urlpatterns = [
    path('', master_budget_dashboard, name="master_budget_dashboard"),
    path(
        'projection-parameters-list/',
        projection_parameters,
        name="projection_parameters"
    ),
    path(
        'projection-parameter-edit/<int:id>/',
        projection_parameter,
        name="projection_parameter"
    ),
    path(
        'profit-and-loss-reports/complementary-projection-list',
        profit_loss_report_complementary_projection,
        name="profit_loss_report_complementary_projection"
    ),
    path(
        'profit-and-loss-reports/complementary-projection-detail/<int:period_id>/',
        profit_loss_report_complementary_projection_detail,
        name="profit_loss_report_complementary_projection_detail"
    ),
]

ppto_safa/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.conf.urls import (
    handler404,
    handler500,
    handler403
)

from apps.main.views import error_500, error_404, error_403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('administration/', include('apps.administration.urls')),
    path('security/', include('apps.security.urls')),
    path('expenses-budgets/', include('apps.expenses_budgets.urls')),
    path('travel-budgets/', include('apps.travel_budgets.urls')),
    path('investment-budgets/', include('apps.investment_budgets.urls')),
    path('staff-budgets/', include('apps.staff_budgets.urls')),
    path('indirect-budgets/', include('apps.indirect_budgets.urls')),
    path('income-budgets/', include('apps.income_budgets.urls')),
    path('cost-budgets/', include('apps.cost_budgets.urls')),
    path('goals/', include('apps.goals.urls')),
    path('master-budget/', include('apps.master_budget.urls')),
    path(
        'master-budget/loan-portfolio/',
        include('apps.master_budget.loan_portfolio.urls')
    ),
    path(
        'master-budget/passives/',
        include('apps.master_budget.passives.urls')
    ),
    path(
        'master-budget/non-performing-assets/',
        include('apps.master_budget.non_performing_assets.urls')
    ),
    path(
        'master-budget/payment-payroll/',
        include('apps.master_budget.payment_payroll.urls')
    ),
    path(
        'master-budget/equity/',
        include('apps.master_budget.patrimony.urls')
    ),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
) + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

handler403 = error_403  # NOQA
handler404 = error_404  # NOQA
handler500 = error_500  # NOQA

apps/master_budget/patrimony/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.main.models import Periodo

from apps.master_budget.models import (
    AuditDataMixin, AmountMonthlyMixin, AmountIncreasesMonthlyMixin,
    MasterParameters
)
from utils.constants import OTHERS_ASSETS_CRITERIA


def is_percentage(value):
    if value >= 0 and value <= 1:
        return True
    return False


class EquityCategory(AuditDataMixin):
    id = models.AutoField(primary_key=True, db_column="Id")
    name = models.CharField(null=True, blank=True, max_length=50, db_column="Nombre")
    is_active = models.BooleanField(null=True, blank=True, default=True, db_column="Estado")
    identifier = models.CharField(null=True, blank=True, max_length=150, db_column="Identificador")
    created_by = models.ForeignKey(User, models.DO_NOTHING, db_column="CreadoPor", null=True, blank=True) # NOQA
    updated_by = models.ForeignKey(
        User, models.DO_NOTHING, db_column="ActualizadoPor", null=True, blank=True,
        related_name="user_update_equity_category"
    )

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroPatrimonioCat"

    def __str__(self):
        return f"{self.name}"


class EquityScenario(AuditDataMixin):
    id = models.AutoField(primary_key=True, db_column='Id')
    period_id = models.ForeignKey(Periodo, models.DO_NOTHING, db_column="PeriodoId", null=True, blank=True) # NOQA
    parameter_id = models.ForeignKey(MasterParameters, models.DO_NOTHING, db_column="ParametroId")
    correlative = models.CharField(null=True, blank=True, max_length=50, db_column="Correlativo")
    comment = models.CharField(null=True, blank=True, max_length=500, db_column="Comentario")
    is_active = models.BooleanField(null=True, blank=True, default=True, db_column="Estado")
    deleted = models.BooleanField(null=True, blank=True, default=False, db_column="Eliminado")
    created_by = models.ForeignKey(User, models.DO_NOTHING, db_column="CreadoPor", null=True, blank=True) # NOQA
    updated_by = models.ForeignKey(
        User, models.DO_NOTHING, db_column="ActualizadoPor", null=True, blank=True,
        related_name="user_upd_equity_scenario"
    )

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroPatrimonioEsc"


class Equity(AuditDataMixin, AmountMonthlyMixin, AmountIncreasesMonthlyMixin):
    id = models.AutoField(primary_key=True, db_column="Id")
    scenario_id = models.ForeignKey(
        EquityScenario, models.DO_NOTHING, db_column="EscenarioId", null=True, blank=True
    )
    category_id = models.ForeignKey(
        EquityCategory, models.DO_NOTHING, db_column="CategoriaId", blank=True, null=True
    )
    category = models.IntegerField(db_column="Categoria", null=True, blank=True)
    category_name = models.CharField(db_column="CategoriaNombre", max_length=150, null=True, blank=True) # NOQA
    previous_balance = models.DecimalField(
        db_column="SaldoAnterior", decimal_places=2, max_digits=23, default=0, blank=True, null=True
    )
    criteria = models.IntegerField(db_column="Criterio", choices=OTHERS_ASSETS_CRITERIA, null=True, blank=True) # NOQA
    comment = models.CharField(db_column="Comentario", max_length=200, default='', null=True, blank=True) # NOQA
    percentage = models.FloatField(db_column="Procentaje", null=True, blank=True, default=0) # NOQA
    new_balance = models.DecimalField(
        db_column="NuevoSaldo", max_digits=23, decimal_places=2, default=0, blank=True, null=True
    )

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroPatrimonio"


class SurplusCategory(AuditDataMixin):
    id = models.AutoField(primary_key=True, db_column='Id')
    name = models.CharField(null=False, blank=False, max_length=100, db_column="Nombre")
    order = models.IntegerField(db_column="Orden", null=False, blank=False)
    action = models.CharField(null=False, blank=False, max_length=5, db_column="Accion")

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroCategoriaExcedentes"
        ordering = ('order',)

    def __str__(self):
        return self.name


class DistributionSurplusPeriod(AuditDataMixin):
    id = models.AutoField(primary_key=True, db_column='Id')
    period_id = models.ForeignKey(
        Periodo, models.DO_NOTHING, db_column="IdPeriodo", null=False, blank=False
    )
    surplus_amount = models.DecimalField(
        db_column="MontoExcedentes", decimal_places=2, max_digits=18, default=0, null=False,
        blank=False
    )

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroDistribucionExcedentesPeriodo"


class DistributionSurplusCategory(AuditDataMixin):
    id = models.AutoField(primary_key=True, db_column='Id')
    id_surplus_category = models.ForeignKey(
        SurplusCategory, models.DO_NOTHING, db_column="IdCategoriaExcedentes", null=False,
        blank=False
    )
    id_dsp = models.ForeignKey(
        DistributionSurplusPeriod, models.DO_NOTHING, db_column="IdDEP", null=False, blank=False
    )
    title = models.CharField(db_column="Etiqueta", null=False, blank=False, max_length=100)
    percentage = models.FloatField(
       db_column="Porcentaje", null=False, blank=False, default=0,
       validators=[is_percentage]
    )
    amount = models.DecimalField(
        db_column="Monto", decimal_places=2, max_digits=18, default=0, blank=False, null=False
    )

    class Meta:
        default_permissions = []
        db_table = "pptoMaestroDistribucionExcedentesCategoria"

apps/master_budget/forms.py
from django import forms

from apps.main.models import Periodo
from .models import MasterParameters
from utils.constants import STATUS


class MasterParametersForm(forms.ModelForm):
    date_base = forms.DateField(
        label="Fecha Base",
        required=True,
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    is_active = forms.ChoiceField(
        label="Estado",
        required=True,
        choices=STATUS,
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    period_id = forms.ModelChoiceField(
        label="Periodo",
        queryset=Periodo.objects.filter(habilitado=True),
        empty_label="--- Seleccione Periodo ---",
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    comment = forms.CharField(
        label="Comentario",
        widget=forms.Textarea(
            attrs={"rows": 3, "style": 'resize:none', 'class': 'form-control'}
        )
    )

    class Meta:
        model = MasterParameters
        fields = (
            'date_base',
            'period_id',
            'is_active',
            'comment',
        )


class MasterParametersEditForm(forms.ModelForm):
    date_base = forms.DateField(
        label="Fecha Base",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'date'})
    )
    is_active = forms.ChoiceField(
        label="Estado",
        required=True,
        choices=STATUS,
        widget=forms.Select(
            attrs={'class': 'form-select', 'style': 'width:100%'}
        )
    )
    comment = forms.CharField(
        label="Comentario",
        widget=forms.Textarea(
            attrs={"rows": 3, "style": 'resize:none', 'class': 'form-control'}
        )
    )

    class Meta:
        model = MasterParameters
        fields = (
            'date_base',
            'is_active',
            'comment',
        )

apps/master_budget/loan_portfolio/forms.py
from django import forms

from .models import (
    LoanPortfolioScenario,
    LoanPortfolioCategory,
    FinancialInvestmentsScenario,
    FinancialInvestmentsCategory
)
from apps.master_budget.models import MasterParameters
from utils.constants import STATUS_SCENARIO


class LoanPortfolioScenarioForm(forms.ModelForm):
    parameter_id = forms.ModelChoiceField(
        label="Parametro de Proyección",
        required=True,
        queryset=MasterParameters.objects.filter(is_active=True),
        empty_label="--- Seleccione Parametro de Proyección ---",
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    category_id = forms.ModelChoiceField(
        label="Categoria",
        required=True,
        queryset=LoanPortfolioCategory.objects.filter(is_active=True),
        empty_label="--- Seleccione Categoria ---",
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    is_active = forms.ChoiceField(
        label="Estado",
        required=True,
        choices=STATUS_SCENARIO,
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    comment = forms.CharField(
        label="Comentario",
        required=True,
        widget=forms.Textarea(
            attrs={"rows": 3, "style": 'resize:none', 'class': 'form-control'}
        )
    )

    class Meta:
        model = LoanPortfolioScenario
        fields = (
            'parameter_id',
            'category_id',
            'is_active',
            'comment',
        )


class ScenarioCloneUpdateParameterForm(forms.Form):
    parameter_id = forms.ModelChoiceField(
        label="Parametro de Proyección",
        required=True,
        queryset=MasterParameters.objects.filter(is_active=True),
        empty_label="--- Seleccione Parametro de Proyección ---",
        widget=forms.Select(
            attrs={
                'class': 'form-select select2-style-clone-update',
                'style': 'width:100%'
            }
        )
    )
    is_active = forms.ChoiceField(
        label="Estado",
        required=True,
        choices=STATUS_SCENARIO,
        widget=forms.Select(
            attrs={
                'class': 'form-select select2-style-clone-update',
                'style': 'width:100%'
            }
        )
    )
    comment = forms.CharField(
        label="Comentario",
        required=True,
        widget=forms.Textarea(
            attrs={"rows": 3, "style": 'resize:none', 'class': 'form-control'}
        )
    )


class ScenarioCloneForm(forms.Form):
    is_active = forms.ChoiceField(
        label="Estado",
        required=True,
        choices=STATUS_SCENARIO,
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    comment = forms.CharField(
        label="Comentario",
        required=True,
        widget=forms.Textarea(
            attrs={"rows": 3, "style": 'resize:none', 'class': 'form-control'}
        )
    )


class FinancialInvestmentsScenarioForm(forms.ModelForm):
    parameter_id = forms.ModelChoiceField(
        label="Parametro de Proyección",
        required=True,
        queryset=MasterParameters.objects.filter(is_active=True),
        empty_label="--- Seleccione Parametro de Proyección ---",
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    category_id = forms.ModelChoiceField(
        label="Categoria",
        required=True,
        queryset=FinancialInvestmentsCategory.objects.filter(is_active=True),
        empty_label="--- Seleccione Categoria ---",
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    is_active = forms.ChoiceField(
        label="Estado",
        required=True,
        choices=STATUS_SCENARIO,
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    comment = forms.CharField(
        label="Comentario",
        required=True,
        widget=forms.Textarea(
            attrs={"rows": 3, "style": 'resize:none', 'class': 'form-control'}
        )
    )

    class Meta:
        model = FinancialInvestmentsScenario
        fields = (
            'parameter_id',
            'category_id',
            'is_active',
            'comment',
        )


class FinancialInvestmentsScenarioCloneForm(forms.Form):
    is_active = forms.ChoiceField(
        label="Estado",
        required=True,
        choices=STATUS_SCENARIO,
        widget=forms.Select(
            attrs={'class': 'form-select select2-style', 'style': 'width:100%'}
        )
    )
    comment = forms.CharField(
        label="Comentario",
        required=True,
        widget=forms.Textarea(
            attrs={"rows": 3, "style": 'resize:none', 'class': 'form-control'}
        )
    )

apps/master_budget/templates/master_budget/shared/pagination_multiple.html
{% load static %}
{% load humanize %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/pagination.css' %}">
{% endblock style %}
<div class="center">
  <div class="pagination">
    <a 
      {% if qs.has_previous %}
      href="?s={{request.GET.s}}&q={{request.GET.q}}&page={{ qs.previous_page_number }}&period={{request.GET.period}}"
      {% else %}
        href="#"
        aria-disabled="true" 
      {% endif %}
    >&laquo;</a>
    <a href="#" class="active">{{qs.number|intcomma}}</a>
    <a 
      {% if qs.has_next %}
       href="?s={{request.GET.s}}&q={{request.GET.q}}&page={{ qs.next_page_number }}&period={{request.GET.period}}"
      {% else %}
        href="#" 
        aria-disabled="true" 
      {% endif %}
    >&raquo;</a>
  </div>
  <p class="fw-normal">
    Pagina {{qs.number|intcomma}} de {{qs.paginator.num_pages|intcomma}}.&nbsp; Total registros: {{qs.paginator.count|intcomma}} 
  </p>
</div>

apps/master_budget/templates/master_budget/shared/pagination_scenarios.html
{% load static %}
{% load humanize %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/pagination.css' %}">
{% endblock style %}
<div class="center">
  <div class="pagination">
    <a 
      {% if qs.has_previous %}
      href="?status={{request.GET.status}}&page={{ qs.previous_page_number }}&category={{request.GET.category}}&parameter={{request.GET.parameter}}"
      {% else %}
        href="#"
        aria-disabled="true" 
      {% endif %}
    >&laquo;</a>
    <a href="#" class="active">{{qs.number|intcomma}}</a>
    <a 
      {% if qs.has_next %}
       href="?status={{request.GET.status}}&page={{ qs.next_page_number }}&category={{request.GET.category}}&parameter={{request.GET.parameter}}"
      {% else %}
        href="#" 
        aria-disabled="true" 
      {% endif %}
    >&raquo;</a>
  </div>
  <p class="fw-normal">
    Pagina {{qs.number|intcomma}} de {{qs.paginator.num_pages|intcomma}}.&nbsp; Total registros: {{qs.paginator.count|intcomma}} 
  </p>
</div>

apps/master_budget/templates/master_budget/shared/search_form_scenarios.html
{% load static %}
<form method="GET">
<div class="row align-items-end justify-content-end">
  <div class="col-md-4">
    <div class="form-group">
      <select name="parameter" id="id_parameter" class="form-select">
        <option value="">-- Parametros --</option>
        {% for i in parameters %}
        <option value="{{i.pk}}">{{i.date_base|date:'d/m/Y'}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  
  {% if categories %}
  <div class="col-md-3">
    <div class="form-group">
      <select name="category" id="id_category" class="form-select">
        <option value="">-- Categorias --</option>
        {% for i in categories %}
        <option value="{{i.pk}}">{{i}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  {% endif %}
    
  <div class="col-md-3">
    <div class="form-group">
      <select name="status" id="id_status" class="form-select">
        {% for key, val in status %}
        <option value="{{key}}">{{val}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="col-md-2">
    <button class="btn btn-outline-primary float-end" type="submit">Buscar</button>
  </div>
</div>
</form>

apps/master_budget/templates/master_budget/shared/search_form_simple.html
{% load static %}
<form method="GET">
  <div class="input-group">
    <input
      name="q"
      value="{{request.GET.q}}"
      type="text"
      class="form-control"
      placeholder="Ingrese filtro de busqueda"
      aria-label="Ingrese filtro de busqueda"
      aria-describedby="button-addon2">
    <button class="btn btn-outline-primary" type="submit" id="button-addon2">Buscar</button>
  </div>
</form>

apps/master_budget/templates/master_budget/shared/search_form_with_period.html
{% load static %}
<form method="GET">
<div class="row">
  <div class="col-md-5">
    <div class="form-group">
      <select name="period" id="id_period" class="form-select" style="width: 100%;">
        <option value="">-- Periodo --</option>
        {% for i in periods %}
        <option {% if request.GET.period == i.pk %} selected {% endif %} 
        value="{{i.pk}}">{{i}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="col-md-7">
    <div class="input-group">
      <input
        name="q"
        value="{{request.GET.q}}"
        type="text"
        class="form-control"
        placeholder="Ingrese filtro de busqueda"
        aria-label="Ingrese filtro de busqueda"
        aria-describedby="button-addon2">
      <button class="btn btn-outline-primary" type="submit" id="button-addon2">Buscar</button>
    </div>
  </div>
</div>
</form>